[php]
version = "8.3"
extensions = [
  "gd",
  "sodium",
  "curl",
  "mbstring",
  "pdo",
  "openssl",
  "dom",
  "fileinfo",
  "filter",
  "hash",
  "pcre",
  "session",
  "tokenizer",
  "xml",
  "ctype",
]

[build]
cmd = "composer install --optimize-autoloader --no-interaction"

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
