<?php

return [
    'public_path' => public_path(),
    'storage_path' => storage_path(),
    'base_path' => base_path(),
    'accepted_protocols' => ['http://', 'https://', 'file:///', 'php://'],
    'allowed_protocols' => ['http://', 'https://', 'file:///', 'php://'],
    'mode' => 'html5',
    'enable_remote' => true,
    'enable_javascript' => true,
    'enable_css_float' => true,
    'enable_php' => true,
    'tempDir' => sys_get_temp_dir(),
    'fontDir' => storage_path('fonts/'),
    'fontCache' => storage_path('fonts/'),
    'chroot' => storage_path('app'),
    'logOutputFile' => null,
    'allowedProtocols' => ['http://', 'https://', 'file:///', 'php://'],
    'allowedRemoteHosts' => [],
    'allowedRemoteProtocols' => ['http://', 'https://'],
    'defaultMediaType' => 'screen',
    'defaultPaperSize' => 'a4',
    'debugKeepTemp' => false,
    'debugPdf' => false,
    'debugCss' => false,
    'debugLayout' => false,
    'debugLayoutLines' => true,
    'debugLayoutBlocks' => true,
    'debugLayoutInline' => true,
    'debugLayoutPaddingBox' => true,
    'pdfBackend' => 'GD',
    'pdflibLicense' => '',
    'adminUsername' => 'user',
    'adminPassword' => 'password',
];
